app:
  name: ${{values.component_id}}
  namespace: ${{values.component_id}}-ai
  cluster: ${{values.cluster}}
  user: ${{values.user}}
  model: ${{values.model}}

git:
  branch: main
  repo: ${{values.source_repository}}
